sections:
  - title: Major changes
    labels:
      - "release/super-feature"
  - title: Complete changelog
    labels:
      - "bug"
      - "enhancement"
      - "dependencies"
template: |
  Add OneCx application maven parent to your project:
  ```xml
    <parent>
        <groupId>io.github.onecx</groupId>
        <artifactId>onecx-quarkus3-parent</artifactId>
        <version>{{ .Version }}</version>
    </parent>
  ```
  {{ range $section := .Sections }}{{ if $section.Items }}### {{ $section.GetTitle }}{{ range $item := $section.Items }}
  * [#{{ $item.GetID }}]({{ $item.GetURL }}) - {{ $item.GetTitle }}{{ end }}{{ end }}
  {{ end }}